### ISSUE TITLE
Some questions ❓

### ISSUE THREAD

**Issue by Slals** [jacobp100/jacob-does-code#2]
Hey Jacob,

I came accross your blog, you were featured in Stack Overflow! [This article](https://jacobdoescode.com/2020/12/30/super-optimised-static-sites)

It's a real nice website, a wonderful job on the design! I got interested on whats going on under the hood and here I am.

Having a little exp. with Jekyll, I know what's the good sides and the bad sides of this solution, I feel like your approach with React is a nice idea that brings more simplicity to build custom re-usable components across the website, with the power of writing pages quite easily with Markdown.

I would be willing to work a bit on this to enhance what can/must be enhanced or fixed and create a builder to scaffold this project for new website, with a default template.

Here are my questions:
- Does it work smoothly with Github pages?
- What are the downside of this approach compared to Jekyll?
- Any benchmark or data to see if the resulting website is lighter and/or faster to load compared to Jekyll?
- What are the top priorities to fix or enhance?

According to your answer I will take a bit of time to rebuild my [website](https://blocs.fr) (running with Jekyll and Github pages) using your approach :)

Nice job Jacob!

**Comment by jacobp100** [comment]
The site is actually run through GitHub pages. There’s a GitHub action that builds the site and commits it to the gh-pages branch. See https://github.com/jacobp100/jacob-does-code/blob/master/.github/workflows/build.yml

I guess for Jekyll, because it has no understanding of what your assets are, you’re kinda free to use whatever. In this system, the tooling has to have some awareness of assets. It wasn’t a problem for me because I could just add support for stuff like videos etc. But it does only support the use cases I came across

My benchmark was going from high 90s on the lighthouse score (with a LOT of hacks in Jekyll to achieve this) to consistently 100

SVG support could be a bit better. Currently it’s done via dangerouslySetInnerHtml, but something that transforms the svgs like svgr would be much better
